### ISSUE TITLE
how to disable odium books dropping 1.19.2

### ISSUE THREAD

**Issue by arcticgalaxies** [TinyModularThings/UniqueEnchantments#101]
I've tried everything to disable them somehow but they wont stop dropping

**Comment by Speiger** [comment]
@Speiger some mods simply ignore the "enabled" flag and drop it too there is not much you can do.
You can deactivate it to so if it is obtained then the functionality will be disabled anyways.

**Comment by arcticgalaxies** [comment]
I'm just tired of them clogging up my inventory with every mob I kill, rip

**Comment by eristacrat** [comment]
Could a mod like item obliterator work for removing it?

**Comment by Xaikii** [comment]
This is getting a small patch in the coming week, the chance is being properly reduced to 2% and the condition is also fixed

**Comment by Xaikii** [comment]
For clarification, the condition and the chance has been fixed.
The condition is now properly on specifically 1-shots, world kills dont count, neither do 5 hit kills.
The chance is also properly to 2%.

Tweaking of the condition and odds is not planned.

**Comment by a-Datana** [comment]
> Tweaking of the condition and odds is not planned.

could you allow for the drop probability to be modified via the config? 
and one hit kill drop to either true or false? 

to be fair, many modded players have strong weapons and mob farms getting 200+ books per minute is pretty bad. 

These configs would neither be hard to implement or bad practice.

**Comment by Xaikii** [comment]
@a-Datana 
the drops of said book is intended to be a halting factor of storage for overpowering, while also allowing easy access to the curse itself.
The special drops are a feature we do not wish to have configs even though they would be quick to do.
It won't reach 200 books per minute, everything around this drop is bugged rn, after the fix it won't be as much anymore.

Any further questions or issues for a config for this feature will be closed.
We provide lots of configs and customization for everything we provide, so we ask you to respect the one time we do not wish something to be configurable.

**Comment by a-Datana** [comment]
> Could a mod like item obliterator work for removing it?

yes use the nbt filter with: 
  "blacklisted_nbt": [
  "uniquee:deaths_odium"
  ],
  to disable it from appearing on any type of item

**Comment by Xaikii** [comment]
closed as resolved with 5.0.1
