### ISSUE TITLE
[1.19.2] !!!RUINS THE GAMES MOST POWERFULL FOOD!!! Enchanted Golden Apple bug

### ISSUE THREAD

**Issue by Vovan-Minecraft** [TinyModularThings/UniqueEnchantments#102]
Whenever you eat EGA(Ench.Golden.Apple) and receive effect Resistance, any damage you receive,
Fall damage, Fire Damage, physical damage, **ONESHOTS YOU,** making the game impossible to beat with this effect, no idea why this happens, but It definetly needs fix.

**Comment by Xaikii** [comment]
Change this line in the mixin.properties, which you'll find in the ue config folder
common.entity.LivingEntityMixin=false
