### ISSUE TITLE
Deaths odium mob drop is to much

### ISSUE THREAD

**Issue by eristacrat** [TinyModularThings/UniqueEnchantments#104]
I have tried two ways to disable death's odium from dropping. Such as, disabling it in the config and using item obliterate mod to disable the NBT. Every time I did this, the game would crash, stating that what file I had modified could not load.  Do you plan to add some way of disabling the death's odium mob drop?

**Comment by Xaikii** [comment]
Duplicate of #101

**Comment by Xaikii** [comment]
`Do you plan to add some way of disabling the death's odium mob drop?`
No, the chance is adjusted, and the special drops are not supposed to be configurable, sry.
