### ISSUE TITLE
Ender Mending

### ISSUE THREAD

**Issue by ReportBot9009** [TinyModularThings/UniqueEnchantments#13]
Hello again,

So this is for Enigmatica 2 Expert on 1.12 Forge 2847

I see from the description how Ender Mending works, but it doesn't seem to work when pieces of armor or tools are at full health with full ender mending storage, and a new, almost broken tool/armor gets the enchant. Nothing happens. The storage doesn't from other armor/tools don't get used for the new pieces on low durability. 

Also, the command /unique_enchantments reloads the config to what the file says in the folder, not the changes I've made in game. I think I said that in my other issue, but not as succinctly.

Anyway, thanks again for the mod. It's one of those mods I can't live without now, lol :)

**Comment by Speiger** [comment]
@ReportBot9009 Sorry for the long delay. We missed this totally. (Thanks to no notification)
The storage for durability is only for the items that the storage is on. That means it does only apply to that tool. Also EnderMending itself does only that extra part. Mending still applies like normal just that the equal distribution gets added.

About the reload:
The reloader can not see any changes you made its simple a notify so you know "Oh it started reloading, oh it is finished".

Also no problem.

**Comment by ReportBot9009** [comment]
Thank you for getting back to me and thank you for the clarifications.
