### ISSUE TITLE
Alchemist Grace's config and effect confusion

### ISSUE THREAD

**Issue by Szadeck** [TinyModularThings/UniqueEnchantments#14]
Hello,

I'm not sure 100% but after some tests i think there is a confusion between the config description of the Alchemists grace enchantment and the real effect it does.

This is the config snippet:

  # Which Potion Effects should be applied. Format: MinimumEnchantLevel;Potion;PotionLevel;BaseDuration [default: [1;minecraft:speed;1;4]

So this line :  "4;minecraft:strength;2;10" should mean that on hit, the player will receive potion "minecraft:strength" effect level "2" for BaseDuration * scalar (well i'm not sure about how exactly the scalar work yet) if your Alchemist race enchant is level 4 minimum.

After testing i figured out that the "PotionLevel" is actually modifying the potion duration (lvl 1 is suppose to be 3min while lvl2 is 8min) but the Potion Level, in this case, is always level 3 minecraft:strength. 

As an example i tried with this "4;minecraft:strength;1;1" and the only thing that changed is the duration (from 2.40 min to 30 second).

If this was planned then i just didn't understand how it works but i feel that  it was not meant to work this way. By the way, with this enchantment i have also recorded that changing the scalar value doesn't change the duration of any potions effect at all. 

Thanks in advance for your time and hope you can explain or fix this.

**Comment by Speiger** [comment]
@Szadeck Sorry we missed our issue reports a bit (we are catching up)

Basically the config works like this:

- The minimum level is basically the level that is required to be applied (of Alchemist Grace's)
- Potion is what potion should be applied
- How Strong the potion effect should be.
- How long this potion should last at least. In Ticks.
duration scalar is a multiplier in seconds of how long the time should last.

The code executes the list in reverse (in terms of the minimum level) from top to bottom.
Starting at the level it is currently in until it reaches level 0.
It ignores all potions that are already applied. So if you have 2x strength in it it will take only the higher one.

I hope this answers your question

**Comment by Speiger** [comment]
https://github.com/TinyModularThings/UniqueEnchantments/blob/1.12.2/src/main/java/uniquee/enchantments/unique/EnchantmentAlchemistsGrace.java#L66

**Comment by Xaikii** [comment]
Just an update on this.
We're working on a patch which should fix any confusion with this Enchantment and it's customization.

For more info how the Enchantment will work post-patch, see the [wiki](https://github.com/TinyModularThings/UniqueEnchantments/wiki/Alchemist%27s-Grace).
