### ISSUE TITLE
[1.16.5] Mod Fails to Load on Server

### ISSUE THREAD

**Issue by HockeyZman2000** [TinyModularThings/UniqueEnchantments#29]
Upon starting up my Minecraft 1.16.5 server, this mod fails to load mentioning "class loading errors" originating from this mod.

Server output log: 
[crash-2021-03-23_02.54.20-fml.txt](https://github.com/TinyModularThings/UniqueEnchantments/files/6187828/crash-2021-03-23_02.54.20-fml.txt)

Any help would be greatly appreciated!

**Comment by Xaikii** [comment]
Noted, expect a Patch within the next days.

**Comment by HockeyZman2000** [comment]
Thanks for the quick response!

**Comment by Speiger** [comment]
Patch will come out within the next few hours.

**Comment by Speiger** [comment]
Patch is out.
