### ISSUE TITLE
[FEATURE] Enchantment Ideas

### ISSUE THREAD

**Issue by Camawama** [TinyModularThings/UniqueEnchantments#31]
Curse of Dullness (anti sharpness)
Curse of XP loss (performing actions that would normally grant XP has a chance to take XP)
Curse of Dilute (When wearing this on armor, drinking potions sometimes doesn't give the effect)
Curse of imperfection (On weapons, has a chance to "miss" a hit)
Curse of Slippery (Has a small chance to drop the item [armor, sword, ax] when it uses durability)

Change of Pace (Allows for easy combos when on a weapon [I have no idea how this would work])
Levitate (When damage is inflicted by an item with this enchantment, causes the entity damaged to float up for 5 seconds)
Anti Levitation (When an enemy is attacked with an item that has this enchantment, the enemy is buried into the ground for 5 seconds)
Carnage (Upgraded sweeping edge. Dealing the same damage to hoards of mobs when one mob is hit)

That's all I got right now. I could think of a million of these though

**Comment by Speiger** [comment]
This will take a while no matter if accepted or not. The next patch eta is at least 2 weeks from now.
(I am not the person who has the final say on what gets added, just that i am the guy who codes it. But if accepted it comes on the todolist)

**Comment by Xaikii** [comment]
Hey, first of all thanks for the Suggestions.
Lets start with the obvious things, Curses are not very popular.
Thus we have a "rule" on what a Curse should be like for Unique Enchantments.
Either the Curse is strong enough to noticeably impact the Gameplay or **CAN** be used for own benefits.
A perfect example for this is Famine's Odium (from the Utils Module), which you can use in your own favor to have automatic eating.
It would also be counter-intuitive to create Curses of which already Enchantments exist.

Looking at the curses with those rules, Curse 1, 2, 3 & 5 are out of the picture (regarding curse 3 & 5, there are Enchantments on the to-do list). 
Curse 4 however is a nice idea, while I wouldn't add it in that exact manner, I have an idea how to implement it. 
If this passes Speigers "reliability test" you might see it in the planned "Battle Module" (might take months till it gets released).

Regarding the non-Curse Enchantments.
You'd have to be a bit more specific with "Change of Pace", were you imagining using different weapons within the same slot, or were you thinking in the likes of our "Perpetual Strike" Enchantment?
Levitate was once in a different shape in our to-do list, however we scratched it, as we considered it to be too cheeseable.
Anti-Levitate is in a similar shape already in our to-do list.
With Enchantments like Carnage, we already said early on too not mess with AoE too much. Hordes are something we want to keep difficult to handle, same goes for Mob Farms which Carnage would affect. With Carnage every Mob Farm that is limited by Mob Count would be buffed percentually as you would get rid of them even faster.

**Comment by Camawama** [comment]
I like how you guys think. I am glad that you think Curse 4 is a good idea! For change of pace, I was more or less focusing on PvP . Wanted to make it so that when a player wielded a weapon with this enchantment (every once in a while) the player can hit from a further distance. It would change PvP to, instead of being solely about who's better, have a bit of randomness. It may help people who don't have as powerful loot have a chance at fighting someone. I understand that combos aren't even really a thing anymore in newer versions of Minecraft, but I know you guys could somehow make this work. Here are just a couple more ideas, I know you guys won't like these all, but the more I put out there, the higher the chance one if them is added.

Curses:
**Curse of Diffidam** (A very rare curse that can appear on armor and makes certain non-hostile or neutral mobs attack on sight like hostiles. Diffidam is Distrust in Latin)
**Curse of Paralysis** (When on armor, any damage that is dealt to the player dealing more than 5 hearts has a chance to grant temporary paralysis [slowness effect or possibly your own])
**Curse of Panic** (If a player has Splash Potions or Ender Pearls and is in a fight and about to die, the potions are automatically thrown out or the ender pearl is thrown in a direction away from the mobs. This may work to benefit the player but at the same time could ruin a players fight if they still thought they could win)
**Curse of Sweet Revenge** (When killed by a mob, instead of the player spawning back at their home, they spawn about 100 blocks near where the mob killed them)
**Curse of Redstone Resonance** (When near redstone for too long, the players body resonates from the redstone current (this doesn't actually happen) but the player will take slight damage when near activated redstone for prolonged periods of time. This could benefit the player by helping them possibly discover redstone traps near where they are)

Non-Curse:
**Passthrough** (I know you said you didn't want to change AoE but this one is slightly balanced. When a player is fighting a hoard of mobs with this enchantment on their weapon, the mobs on the front line will not be damaged by the players attack, rather, the mobs directly behind will be hit instead. If you have two zombies (one behind the other) and try to attack the one in the front, the one in the back will be damaged. Once killed, the one in the front will be able to take damage. This could be considered a curse but I thought it was pretty cool)
**Timed Attack** (When the player is fighting, there is a chance that their attack speed is slightly increased for a short period of time)
**Blast Healing** (When an explosion damages the player, their armor can be slightly repaired. This blast still causes damage to the player, thus, preventing the player from blowing themselves up with many TNT to repair armor)


That's all I got currently. Going to head back to working on my modpack!

**Comment by Xaikii** [comment]
I'll keep short.
Curse 1 feels more like a Game rule or "difficulty" Mod Feature, pass on this one.
Curse 2-5 have interesting ideas, which however I yet again wouldn't implement like that, more likely as a Drawback of an Enchantment, combined with a more positive Part. That being said I fully understand the intentions of those.
Also I assume at Curse 5, you mean, that the player receives an Indicator that Redstone is nearby, like Screen getting a Red Tint (e.g. at the Edges of the Screen) .

"Passthrough" is definitely a Curse in this very state. Considerable to implement in the Battle Module.
"Timed Attack" is pretty much already a thing with Alchemist's Grace.
"Blast Healing", interesting idea, I'll see what I can do with it.

Finally "Change of Pace", we already tried messing with Attack Range... didn't go well, that being said there are others way to go for a similar result. Again a Considerable Enchantment.

**Comment by Camawama** [comment]
I love giving ideas. I can probably think of some more at some point. Thank you for responding and thinking about using the ideas! Have a nice day :)

**Comment by Xaikii** [comment]
All Enchantments I found a use for were added into the Ideas List. Once we get to add more Enchantments we'll decide if and which Enchantment will be added.
I'll close this Issue, if you have more Ideas, simply reopen this Issue.
