### ISSUE TITLE
Super log spam

### ISSUE THREAD

**Issue by someaddons** [TinyModularThings/UniqueEnchantments#34]
Even more log spam

https://github.com/TinyModularThings/UniqueEnchantments/blame/1.16.5/src/main/java/uniquee/utils/IdStat.java#L100

Remove the darn system out please, next time at least use a logger

**Comment by Speiger** [comment]
Oops.
This was a debug test that was missing. Also System.out is still a logger xD even if it is the most direct way

**Comment by Speiger** [comment]
Fixed and patch was submitted to curseforge

**Comment by someaddons** [comment]
xD ye the issue is that finding the cause of the system out is harder since it doesnt log which mod it does

**Comment by Speiger** [comment]
Yeah, but for a temp logger that has no use outside of a indev test thing I won't create one. If i have like logging everywhere if i have beta tests running then i would do it. But a single: Am i working testdebug. I rather use easiest accessible logger.
In 1.7.10 it was FMLLog.getLog().info("TestMyThing"); now its System.out.println("TestMyThing");
