### ISSUE TITLE
UniqueEnchantments still obtainable with lootr?

### ISSUE THREAD

**Issue by zEpiixz** [TinyModularThings/UniqueEnchantments#35]
So i set all the values to zero from vitae, enabled = false everywhere.
But somehow some things still just appear in chest. Is it maybe because of the lootr chests and how they use the loot table

**Comment by Xaikii** [comment]
Enabled decides if the Enchantment is regularly obtainable.
Active decides if it got an effect or not.

That being said, if the Enchantment still appears as Loot by Lootr, that means Lootr doesn't check if the Enchantment is obtainable or not. 
If you don't want the Enchantment to have any impact you can use the "active" config, turn it to false.
However if you want to make it special, but still useable you might have to contact the Lootr Dev and report this.

In case, Lootr does everything properly, pls notify us, and we take a look what it might be.

**Comment by zEpiixz** [comment]
Will forward to them thanks for the quick response!
