### ISSUE TITLE
Pestilences Odioums unlocalized name mistyped in en_us.lang

### ISSUE THREAD

**Issue by Leonetienne** [TinyModularThings/UniqueEnchantments#4]
Because of this, the enchantments name is enchantment.someshit.name.

I just fixed the name of the key in en_us.lang and now it works (in my installation).

**Comment by Speiger** [comment]
Fixed in c1e7747
Will be out this weekend. I am right now finishing up the next patch which I don't know if I can do today because its much work and I am kinda ill.
Thanks for the report.
(Will be closed with the release of the mod)
