### ISSUE TITLE
[1.12] Issue with Scape and Run: Parasites

### ISSUE THREAD

**Issue by Sereath** [TinyModularThings/UniqueEnchantments#40]
Any idea of what could be going on here? Came out of nowhere after playtesting a server for over 2 weeks.

https://gist.github.com/Aeron216/6c886d4d6465daaf727af739d4d4e533

https://gist.github.com/Aeron216/7f250ef2203ea343f18ec1adb82056fd

https://gist.github.com/Aeron216/f11b53c803f059389b137e77c5950ab3

The lead developer for SRP has no idea either so far.

The only thing I could think of is a zombie spawning with an enchanted piece with UniqueE and getting attacked by a mob from SRP. However I already doubled checked and RoughMobs2 is set to only enchant zombie gear with vanilla enchantments.

The server right now is stuck crashing as soon as someone tries to get in:

https://gist.github.com/Aeron216/446a8beb27fa0ef94d9ecf341d382bb4

**Comment by Xaikii** [comment]
Hey there,

thanks for the issue.
I've looked through everything and to be frank this seems to be more of an interaction issue between 2 mods.
'Unique Enchantments' Enchantments are compatible to be used by Mobs and Player, and regarding Entities using our Enchantments was already tested, and is actively shown in Modpacks like Roguelike Adventures and Dungeons.

While I can not confirm my assumption rn, we'll look into it, but as I said, I think this is rather something interacting with each other.

Looking at the Log, this is currently happening with our Enchantment "Perpetual Strike", you can change the config "activated" and set it to false, which will disable its entire functionality for now, until we have resolved this issue.

**Comment by Sereath** [comment]
Thank you, that did it.

It's just an unfortunate interaction because other than that, Unique Enchantments has some of the highest quality enchants out there. I have really enjoyed using this mod over the last year and soon enough will be releasing a modpack featuring it.

**Comment by Xaikii** [comment]
Thank you for the kind words :)
We try to keep the Enchantments in a spot that enhances Gameplay as something called "Enchantments" should be from the start. 
As my personal stance with Enchantments is, that they should enhance you, and not the game, we offer a plethora of possibilities one as good as the other :)
With further customization to give PackDevs the possibility to tweak everything to their needs.

As for the issue, I think we have found Issue, however a fix will most-likely only happen in weeks from now
