### ISSUE TITLE
[1.16.5] Crash on ticking entity

### ISSUE THREAD

**Issue by thefnitalian** [TinyModularThings/UniqueEnchantments#41]
I recieved a crash with a ticking entity with this mod. The pastebin follows: https://paste.ee/p/vWKfs

**Comment by Speiger** [comment]
Thanks will be addressed in the next patch which should come "soonTM".
(MC modding is slow for me right now but i try to finish it this week, but no promises on that)

**Comment by Speiger** [comment]
should be addressed.
