### ISSUE TITLE
Broken recipe for Wrapped Enchantment in jei compat code causing absoulely huge nbt inputs table to be spammed into log

### ISSUE THREAD

**Issue by NighthowlerStudios** [TinyModularThings/UniqueEnchantments#44]
[21:53:13] [main/ERROR]: Found a broken recipe: uniquebase.jei.WrappedEnchantment@7ad2ab6d
Outputs:
Inputs: (then proceeds to list every hecking item in the modpack, lasting around 1000 lines)

**Comment by Speiger** [comment]
Could you provide a error log so i can see the lines of code that actually fail?

**Comment by NighthowlerStudios** [comment]
[latest.log](https://github.com/TinyModularThings/UniqueEnchantments/files/7715046/latest.log)

**Comment by NighthowlerStudios** [comment]
mc 1.16.5

**Comment by NighthowlerStudios** [comment]
error begins on line 7304 and is the entire line somehow (word wrap helps here)

**Comment by NighthowlerStudios** [comment]
error continues by showing the exception trace

https://pastebin.com/EMSGnjJk

**Comment by NighthowlerStudios** [comment]
ignore the security craft ones, I have those on a separate issue tracker.

**Comment by Speiger** [comment]
Yeah the list is so long because there is a enchantment that has basically accepted every single item including air.
I will make a hotfix. Give me like 5 mins to start up the ide

**Comment by NighthowlerStudios** [comment]
please make sure to mention the fix here so that I can mention this issue to security craft devs if they have a hard time hotfixing their own blocks, I have a slight memory of attempting to report it to them before but they rejected fixing it

**Comment by Speiger** [comment]
The fix is fairly simple: Just add checks to remove "empty" items. It comes down to checking every single item that it isn't air.
Some mods out there seem to provide "air" items in their Creative Tabs... Which is a wonder why it already didn't cause existing issues.

All i did was ban items that throw out illegal itemstacks...

**Comment by Speiger** [comment]
Small food for thought: If security craft already has its own issues with empty items (air) then it might be the cause.
UE just didn't have a protection against the issue but wasn't causing it. Now you get the protection implemented.

**Comment by NighthowlerStudios** [comment]
I wonder if your fix will patch theirs up to then, sounds interesting.  I'll let you know when I get the patch off curse.  gonna mention this issue in the security craft mod

**Comment by NighthowlerStudios** [comment]
note that reinforced blocks aren't actually craftable on a table, they are required to be made by right clicking the block with an item

**Comment by NighthowlerStudios** [comment]
security craft seemingly has done the same hotfix on their end.  will take around a week before I can fully test things.  I will be watching curse :)

**Comment by Speiger** [comment]
I am already uploading my patch to curseforge. Just was distracted by something else.
Edit: Should be validated any second now.

**Comment by NighthowlerStudios** [comment]
issue has been patched successfully for this mod, thanks a bunch
