### ISSUE TITLE
How do I use Alchemist Blessing

### ISSUE THREAD

**Issue by JettJ377** [TinyModularThings/UniqueEnchantments#45]
There's this enchantment called "Alchemist Blessing" that can supposedly "transmute items" but I don't know how. All I know is that it needs a beacon
I'm using the latest 1.12.2 version

**Comment by Xaikii** [comment]
You need an anvil, Shift-rightclick it with your Tool with Alchemist Blessing, it will then transfer Redstone into the Tool. 
Then you need a beacon, throw the items to transmute on the beacon, and rightclick the Beacon.
A list of what can be transmuted can be found [here](https://github.com/TinyModularThings/UniqueEnchantments/wiki/Alchemist%27s-Blessing).
If the item is not on the list, it will turn into EXP. If you have no more Redstone in your Tool, it will consume durability

**Comment by JettJ377** [comment]
Do you right click it with the item enchanted

**Comment by Speiger** [comment]
Yes

**Comment by JettJ377** [comment]
I tried that, but it didn't work

**Comment by Xaikii** [comment]
is your beacon actived? Do you get the benefits of that beacon?

**Comment by JettJ377** [comment]
oh I never gave it any effects, next time i'll try that and see if it works

**Comment by JettJ377** [comment]
It works

**Comment by Speiger** [comment]
Ok closing.
