### ISSUE TITLE
Keybind for sages soul 1.16 

### ISSUE THREAD

**Issue by Anacromacia** [TinyModularThings/UniqueEnchantments#46]
due to the item im using requiring shift+rightclick for actions, is there a way to assign a new keybind to the enchantment, and if any others require keybinds, those too?

**Comment by Anacromacia** [comment]
turns out i was an idiot and forgot to check the state of the anvil

**Comment by Speiger** [comment]
Best issues that exist. Ones that autoresolve themselve.
Thank you for that treat.
