### ISSUE TITLE
Adept enchantment breaking

### ISSUE THREAD

**Issue by PinkytheYoshi** [TinyModularThings/UniqueEnchantments#48]
Adept enchantment prevented tools with efficiency from being able to break blocks. 
Tested with adept 1 and adept 3 on an efficiency 5 pickaxe.

**Comment by Speiger** [comment]
already fixed.
The patch isn't just done yet. Might take a week or two.

**Comment by PinkytheYoshi** [comment]
Cool. Thanks for the quick reply and letting me know about it.
    On Thursday, January 20, 2022, 06:51:57 PM CST, Speiger ***@***.***> wrote:  
 
 


already fixed.
The patch isn't just done yet. Might take a week or two.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Speiger** [comment]
@PinkytheYoshi 
https://github.com/TinyModularThings/UniqueEnchantments/commit/798ee7296e772e4aec4b8a7101aa0ea5e2f22783#diff-f50a065788768319d7ddbc94316dfebf2b25a916e637abfd4ff667e8697a2040R677

This is the fix that addresses the issue.
