### ISSUE TITLE
Minecraft log circular output GL error

### ISSUE THREAD

**Issue by gtf016** [TinyModularThings/UniqueEnchantments#49]
I tried two loading configurations,I found that unique enchantments utils will cause some problems. I will attach my log file. I hope it can be helpfu
[logs.zip](https://github.com/TinyModularThings/UniqueEnchantments/files/8055984/logs.zip)
l

**Comment by Speiger** [comment]
@gtf016 does this happen with ONLY UE installed?

**Comment by gtf016** [comment]
No, but with utility expansion, this problem will occur.The forge I use is 36.2.26, the MC version is 1.16.5, and the graphics card is gtx1050.At first, I suspected that it was a graphics card driver problem, but the problem was not solved after updating the driver
I'm in China, if jet lag affects your rest I'm deeply sorry

**Comment by Speiger** [comment]
@gtf016 i mean with "ONLY UE" i mean UE + Expansion but no other mods?
Also UE has 0 rendering in the main menu. There is only certain rendering if you have enchantments equipped.
So it would be nice if you can reproduce this with only UE enchantments installed.

**Comment by gtf016** [comment]
Unfortunately, I can't reproduce this problem after loading the same mod last time. Maybe this problem is small-scale and accidental
