### ISSUE TITLE
ranged 2/3/4 not effective against mobs

### ISSUE THREAD

**Issue by superon** [TinyModularThings/UniqueEnchantments#5]
that's about the size of it, during my testing at least this is my assumption.  looks like the range is applied for picks to destroy/remove blocks but when it comes to reaching mobs there is no effect beyond ranged 1.  thus applying anything above range 1 to a sword is utterly pointless... or perhaps i'm missing something that should be obvious

**Comment by Speiger** [comment]
Yep range had a misscalculation and basically negating all damage. That is fixed in the next version.

**Comment by Speiger** [comment]
Next patch should if everything goes well come out today.

**Comment by Speiger** [comment]
Fixed in latest patch
