### ISSUE TITLE
[1.16.5 - utils addon] Null pointer exception when tool enchanted book dropped as loot and the book gets ticked anyway

### ISSUE THREAD

**Issue by Colin-J-Wood** [TinyModularThings/UniqueEnchantments#50]
happened whilst I was playing on dedicated server.  Crashes client only, server remains up

https://pastebin.com/U0LuiurA

**Comment by Colin-J-Wood** [comment]
my theory is the crash occurs because your mod tries to consider the enchanted book as an ordinary tool, which returns null since the item would have no tool-inherited attributes.  the fact it only crashed the client side though is weird.

**Comment by Xaikii** [comment]
could you specify what you mean by "tool enchanted book"?

**Comment by Colin-J-Wood** [comment]
> could you specify what you mean by "tool enchanted book"?

any enchanted book provided by the utils addon that affects a tool such as a pickaxe, axe, shovel, but not a weapon such as a sword

**Comment by Colin-J-Wood** [comment]
I was killing Champion mobs which in their loot table is specified to drop a random enchanted book with levels, and it ended up dropping a util addon enchantment, which crashed the client after a few seconds of sitting there.  this does not happen with any other mods' enchantments

**Comment by Xaikii** [comment]
can you figure out which Enchantment that is?

**Comment by Colin-J-Wood** [comment]
it's possible though, due to how many mobs I was battling at the time, that maybe it occured because an entity was actually generated to hold a specific item with an enchantment provided by utils, and it may have attempted to use the tool as a weapon, resulting in the crash. 

I will test both scenarios and report what I find

**Comment by Colin-J-Wood** [comment]
well...any attempt to reenter the same world now results in an internal server error and kicks me.  server is spitting out something now.  one sec whilst I pastebin it

**Comment by Colin-J-Wood** [comment]
seems to be a crash related to a separate mod, irrelevant to this one, once I fix it I will continue testing.

**Comment by Colin-J-Wood** [comment]
[11:51:39] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Attempted to load class net/minecraft/client/resources/I18n for invalid dist DEDICATED_SERVER

does this method get fired by your library by any chance?  it's what's locking me out of my world after that utils crash happened.

**Comment by Colin-J-Wood** [comment]
nope, that crash was caused by spartanweaponry.  reporting that one to them now.  resuming testing on your mod in a moment

**Comment by Colin-J-Wood** [comment]
I am having trouble reproducing the crash (it is extremely rare) but I have belief in the indexes of the mixins involved.  I believe it could be due to the Resonance enchantment since the main listeners were related to sound.  Whether it be a fault where an entity attempts to fire it which causes the sound to not see a player to play the sound at, or the book itself is ticking for whatever reason, I am not sure.

**Comment by Speiger** [comment]
That bug is the keybinding bug in ueUtils which is addressed with the next patch.

**Comment by Speiger** [comment]
Rough ETA can move into either direction: By next week there should be a release until everything goes wrong in my schedule which is like a 45% likelihood.
