### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by ChromaPIE** [TinyModularThings/UniqueEnchantments#51]
Unique+Enchantments+Base-1.16.5-1.3.0
Unique+Enchantments-1.16.5-2.2.0
Unique+Enchantments+Utils-1.16.5-1.6.0
Unique+Enchantments+Battle-1.16.5-1.3.0

Log: https://paste.ubuntu.com/p/cptPZZSsyj/

Seems like it's conflicting with [Balanced Enchanting](https://www.curseforge.com/minecraft/mc-mods/balanced-enchanting), the last version of UE suite worked just fine.

**Comment by Speiger** [comment]
Incompat with balancedenchanting
UE also does what balanced Enchanting does too now. Its disabled in the configs by default but we can't disable the mixins for it.

**Comment by ChromaPIE** [comment]
Okay the feature is exactly what I want, gonna enable that and remove Balanced Enchanting. Thanks for the support!

**Comment by Speiger** [comment]
Ok just to clearify what UE does with its override:
Instead of taking 3 levels, it takes 3 levels worth of XP, which the balanced Enchanting seems to be doing too.

**Comment by ChromaPIE** [comment]
Got it and that's exactly what I want. Thanks very much:>
