### ISSUE TITLE
client crashing on startup

### ISSUE THREAD

**Issue by mattrix444** [TinyModularThings/UniqueEnchantments#52]
https://pastebin.com/EaW46pih here is the crash. confirmed culprit as it loads fine when i remove UE base

**Comment by mattrix444** [comment]
turns out its an incompatibility with charm or basically anything that adds enchantments.

**Comment by mattrix444** [comment]
turns out its an incompatibility with charm or basically anything that adds enchantments.

**Comment by Xaikii** [comment]
That above really the crash log?

**Comment by Xaikii** [comment]
@mattrix444 looking into the log, it is a problem with our mod and charm
we'll be looking into it

**Comment by Juicylene** [comment]
i just came here to post an issue about the same thing, but my situation seems to be different as i dont have charm installed (so maybe quark is crashing it too???). Here's my crash log for more information:

[crash-2022-04-14_17.25.53-client.txt](https://github.com/TinyModularThings/UniqueEnchantments/files/8492044/crash-2022-04-14_17.25.53-client.txt)

**Comment by Xaikii** [comment]
@Juicylene that is a problem with us and allurement.
We'll look into it

**Comment by Juicylene** [comment]
oooh ok, thx alot for looking into it

**Comment by Speiger** [comment]
@Juicylene thanks for the wait. I threw out a patch that should hopefully fix this...
The Tooltip generation code that causes this crash now only  runs when the player actually exists before that it just disables itself.
This should fix most crashes.

Version 1.3.1 has been uploaded to curseforge it should be out by the time you read this comment.

**Comment by mattrix444** [comment]
sadly the new version of "base" does not solve the problem it still errors with charm.mixin and yes anything other mod that adds its own enchants has conflicts also as ive tried it with quark, apotheosis and some others

**Comment by mattrix444** [comment]
sadly the new version of "base" does not solve the problem it still errors with charm.mixin and yes anything other mod that adds its own enchants has conflicts also as ive tried it with quark, apotheosis and some others

**Comment by Speiger** [comment]
@mattrix444 sadly your crashlog does not show anything about UE causing crashes.
It only shows some startup texts and then stops, anyhting in there is not useful to a fix a crash. If you provide a more useful crashlog or modlist that we can use to replicate it, (and i mean not having to install 70 mods or anything in that range) I can try to replicate it myself. 

Edit: Your "crash log" is not even a crashlog. It is part of the startup log that has been cut off. So unless you provide an actual crashlog/way to reproduce it then I can look at it, otherwise I deem it "Not an issue"

**Comment by Xaikii** [comment]
@mattrix444 to clarity the confusion, pastebin is cutting the text so we first didnt see the whol log.

We know what is causing it, but the earliest we can fix it is after the weekend

**Comment by mattrix444** [comment]
Oh wow I'm a dumb dumb I didn't realise the log was chopped. Sorry for that I definitely copied the whole log so not sure of why that happened. That's fine take your time guys enjoy the weekend. Looking forward to trying it out. Close this if you desire.

**Comment by mattrix444** [comment]
Oops I closed it by accident but no reason to open. Thanks

**Comment by mattrix444** [comment]
https://paste.ee/p/A6sTI here is the current crash log with the newly update 1.3.2 version of base. shouldn't be cut off now

**Comment by mattrix444** [comment]
https://paste.ee/p/A6sTI here is the current crash log with the newly update 1.3.2 version of base. shouldn't be cut off now
