### ISSUE TITLE
Unique Enchantments crash

### ISSUE THREAD

**Issue by Powerkhan** [TinyModularThings/UniqueEnchantments#53]
trying to add these into my modpack customizing one i'm making for 1.16.5 i get this crash report. (see file)
[crash-2022-04-14_23.53.23-client.txt](https://github.com/TinyModularThings/UniqueEnchantments/files/8493743/crash-2022-04-14_23.53.23-client.txt)

**Comment by Speiger** [comment]
Unique Enchantments Base-1.16.5-1.3.0.jar You are running on a outdated version. I just updated the fix.
