### ISSUE TITLE
Crash on pointing at specific item in the inventory

### ISSUE THREAD

**Issue by ChromaPIE** [TinyModularThings/UniqueEnchantments#54]
The game suddenly crashed upon hovering cursor on a fishing rod in the inventory.

Crash report: https://bytebin.lucko.me/vHiVmVWJZn

**Comment by Speiger** [comment]
ok found the problem. Could you come into discord?

**Comment by ChromaPIE** [comment]
Sure

**Comment by Speiger** [comment]
For Everyone else.
Issue is fixed will be released tomorrow, I don't want to make 1 fix every 5-10 minutes so i am batching bugfixes together.
