### ISSUE TITLE
Error spam in log when I unbind any UE key in controls.

### ISSUE THREAD

**Issue by TheJessaChannel** [TinyModularThings/UniqueEnchantments#58]
[00:51:26] [Render thread/ERROR] [minecraft/MainWindow]: ########## GL ERROR ##########
[00:51:26] [Render thread/ERROR] [minecraft/MainWindow]: @ Pre render
[00:51:26] [Render thread/ERROR] [minecraft/MainWindow]: 65539: Invalid key -1

When I unbind any UE key in controls by clicking ESC on the key. I have so many mods so I need all the keys and unbind on keys I am not going to use.

**Comment by Speiger** [comment]
will be addressed in the next patch until then just bind all of them to an key that you dont need at all. (You can bind them to the same key)

**Comment by Kaleidio** [comment]
oh it's an input issue?  I will await the new patch for this as well.  I thought it was related to the tooltip rendering.

**Comment by Speiger** [comment]
Sry that this took so long. We just had a patch begun. But the bug is now fixed, and will be uploaded within this week.
