### ISSUE TITLE
[Relative Issue Investigation Request] Concurrent Modification Exception crash when loading new resources on Parry This!

### ISSUE THREAD

**Issue by NighthowlerStudios** [TinyModularThings/UniqueEnchantments#59]
Crash reports on another mod that builds its own tooltips, Parry This!, state a concurrent modification exception building tooltips that refer to its provided tags.  Your mod is among other custom tooltip mods that crash in this fashion.  I feel parry this is the core of the issue, such as not registering tags before renderers, but your mod is involved so I felt it best to include this here.

https://github.com/theishiopian/Parrying/issues/21

**Comment by NighthowlerStudios** [comment]
closing, issue confirmed fault of another mod that unique enchantments mixins took additional blame for via domino effect

**Comment by Speiger** [comment]
@Kaleidio love these self solving issues!
