### ISSUE TITLE
Ender Marksman duplicates arrows under certain circumstances.

### ISSUE THREAD

**Issue by katubug** [TinyModularThings/UniqueEnchantments#6]
Hi! I'm doing some testing of the various enchantments to decide which fit my pack and which don't, and I'm having some issues with Ender Marksman. Firstly, in terms of balance I find it a little overtuned? What would be great is if we were able to decide how much durability to restore, or even better - if we could define a % chance for the special ability to proc on hit. Because having it be a 100% chance as long as you hit your shot is a little at odds with the difficulty of my pack (I shouldn't speak for others), but I'd rather not disable the enchantment altogether.

Anyway, the main issue is this: If you are using potion-tipped arrows, but you have any vanilla arrows in your inventory - when you hit a shot, you'll get your tipped arrow back, *and* it will give you a vanilla arrow as well. Here's a gif: https://gfycat.com/quarrelsomepoliticalchuckwalla

Minecraft: 1.12.2
Forge: 2847
Unique Enchantments: 1.8

**Comment by Speiger** [comment]
Does that happen also with other mobs?
I will look into that.

**Comment by katubug** [comment]
I was able to replicate it on some vanilla passive animals, yes. I actually just loaded up a totally new instance with just UE and JEI, and tested it out on some cows. Now it seems that when the potion arrow (tested with Fire Resist and Leaping) is in the first slot, it dupes both the potion arrow and the vanilla. If vanilla is first, it only dupes the vanilla arrow.

**Comment by Speiger** [comment]
ok this will be fixed in the next patch.

**Comment by Speiger** [comment]
Ok this was not a duplication glitch.
This was a desync. Because Forge started throwing events on clients too and I didnt check for client because it was serverside only before.

Anyways its patched @katubug
