### ISSUE TITLE
Ares Grace desc not set right (1.12)

### ISSUE THREAD

**Issue by VanyaBaou** [TinyModularThings/UniqueEnchantments#61]
**enchantment.uniqueebattle.ares_grace=Ares Grace
enchantment.uniqueebattle.ares_grace=Increased Damage against protected Enemies**

![image](https://user-images.githubusercontent.com/97327658/174447044-db61d18e-0d5c-43ef-9221-0ed15d4a1281.png)

**Comment by Xaikii** [comment]
Known, already fixed in dev version
