### ISSUE TITLE
Reinforced makes the attack speed of the player faster instead of slower as intended.

### ISSUE THREAD

**Issue by NighthowlerStudios** [TinyModularThings/UniqueEnchantments#63]
Testing shows that the value is calculating in reverse somehow.  Reinforced X makes the diamond sword I tested with feel almost twice its attack speed.

**Comment by Xaikii** [comment]
sry for late response, 
while that is not intended, consider it a feature for now till the next patch or hotfix

**Comment by Speiger** [comment]
Fixed
