### ISSUE TITLE
1.16.5 unique enchantments causes exit code 1 crash

### ISSUE THREAD

**Issue by silvertheidiot** [TinyModularThings/UniqueEnchantments#66]
The unique enchantments mod keeps crashing my game, can't seem to find how to fix it.
Mod list:
![image](https://user-images.githubusercontent.com/111220179/189185929-834856bb-0a7f-461a-bbdb-aef49334eb7f.png)
![image](https://user-images.githubusercontent.com/111220179/189186120-29c8ed8d-1785-439f-b428-62291ca5554b.png)

**Comment by silvertheidiot** [comment]
Also here's a server log that I am trying to open with the same mod list
Log: https://mclo.gs/BZMb497

**Comment by Speiger** [comment]
taxfreelevels-forge.mixins.json:FlattenAnvilCostMixin

That is your problem.
UE has a mixin  that changes level costs on anvils/enchantment tables (that is disabled by default but the mixin still loads)
That turns it from requring 30 levels for example to 30 levels worth of XP making if you are level 70 not level 40 but more like 68 or something like it.
