### ISSUE TITLE
[UniqueTools, 1.16.5] Climber enchantment's effect is active regardless if any tools have it applied or not

### ISSUE THREAD

**Issue by NighthowlerStudios** [TinyModularThings/UniqueEnchantments#67]
self explanatory.

**Comment by NighthowlerStudios** [comment]
disabling it in the config does not fix the issue

**Comment by Speiger** [comment]
will be fixed in the next patch. But might take until October before that comes out.
I am fully busy until that with IC2Classic...

**Comment by NighthowlerStudios** [comment]
Absolutely no problem.  As a fellow dev I relate.  Been grinding out modpack development ya see.  So I've been giving proper testing to issues and making sure to develop proper reports to devs.

**Comment by NighthowlerStudios** [comment]
I discovered that it may be a mod conflict as removing half of my mods from the modpack fixes the issue even tho removing unique enchantments utils also fixed it.  I'm having a lot of trouble finding which mod is conflicting though.
