### ISSUE TITLE
[UniqueEnchant, 1.16.5] Chance to hit entities behind a wall mined with a pickaxe due to Reach

### ISSUE THREAD

**Issue by NighthowlerStudios** [TinyModularThings/UniqueEnchantments#68]
Difficult to replicate, usually done via "corner" hitting the block until the moment it breaks where the entity receives damage.  Has a range further than usual combat range (2.5 blocks, in these instances it's as far as 6 or so) which shouldn't be possible even with the combat mods I tested this alongside.  Occurs even whilst disabled in the config nor applied to the tool, but has a higher chance if it is on the tool used.

**Comment by Xaikii** [comment]
I'll try to replicate it,
but I just want to confirm, "Reach" or "Range"?
"Reach" would be Ensorcellation

**Comment by NighthowlerStudios** [comment]
Range.  I constantly confuse the name.  Whichever is provided by UE as I never installed Ensorcellation

**Comment by Xaikii** [comment]
alright, 
also considering that you've already created multiple issues, wouldnt it make sense to join our discord or add me? ^^'
[discord](https://discord.gg/EHpb6JCPkW) or Xaikii#5318

**Comment by Speiger** [comment]
@Kaleidio we only use the Forges EntityAttribute to change the reach.
So what you are reporting would be a forge bug.

**Comment by NighthowlerStudios** [comment]
> @Kaleidio we only use the Forges EntityAttribute to change the reach. So what you are reporting would be a forge bug.

actually that would make a lot of sense.  I am aware that misbehaviour comes about from trying to mess with it and generic.attack_speed due to some weirdness as i attempted to datapack it once upon a time.  So i guess this issue isn't fixable on your end.
