### ISSUE TITLE
1.16.5 Server - Ticking Entity

### ISSUE THREAD

**Issue by Guest95300** [TinyModularThings/UniqueEnchantments#69]
[crash-2022-10-25_11.30.07-server.txt](https://github.com/TinyModularThings/UniqueEnchantments/files/9859854/crash-2022-10-25_11.30.07-server.txt)

**Comment by Speiger** [comment]
@Guest95300 what entity did you attack?

**Comment by Guest95300** [comment]
My friend caused the crash and he said that a bunch of zombies were attacking him near a zombie spawner

**Comment by Xaikii** [comment]
This issue is already resolved, but the fix is not released yet, as we work on a patch, it will be fixed with it.

Meanwhile you can disable "Perpetual Strike" in the config, which will resolve the issue.
