### ISSUE TITLE
Phoenix's Blessing compatibility with Bauble of Undying

### ISSUE THREAD

**Issue by katubug** [TinyModularThings/UniqueEnchantments#7]
Hi! The modpack I'm working on uses both this mod, and another mod called [Bauble of Undying](https://www.curseforge.com/minecraft/mc-mods/bauble-of-undying).

Phoenix's Blessing functions just fine when the totem is in the player's offhand. However, when the enchanted totem is placed in the baubles slot, the totem saves the player, but it does not fully restore health and hunger.

Minecraft: 1.12.2
Forge: 2847
Bauble of Undying: 1.0.1
Unique Enchantments: 1.8

**Comment by Speiger** [comment]
Thats because we don't have baubles support.
We tried keeping dependencies (in moddev area) low

**Comment by katubug** [comment]
That is fair. I'll close this then. :)
