### ISSUE TITLE
[1.16.5] Pre-load crash with today's update 1.4.1 (and ascociated module versions)

### ISSUE THREAD

**Issue by AlienXtream** [TinyModularThings/UniqueEnchantments#70]
as title says. crashes pre-load. literally during the "early FML setup" window. other than confirming it happens on a clean install with forge 36.2.39
[latest.log](https://github.com/TinyModularThings/UniqueEnchantments/files/9946793/latest.log)

**Comment by NighthowlerStudios** [comment]
This issue was also reported to the discord server and confirmed.  Devs will be on it soon.

**Comment by Xaikii** [comment]
Fix is on the way
