### ISSUE TITLE
Enchantment apex suggestion

### ISSUE THREAD

**Issue by edotenseilove** [TinyModularThings/UniqueEnchantments#75]
Hello, Great and unique mod I would like to suggest the addition of a special enchantment:

Truly fortunate:

This enchantment would work just like fortune but instead of a chance to trigger the effect more drops would be guaranteed depending on the level of the enchantment. Also having this enchantment would always set the drops to one (or min) item plus one per level of the enchantment.

Incompatibility with silk touch and fortune

P.S.: To achieve the same effect I had to create a datapack where I overwrote every ore´s type of fortune formula applied on the block end then set up the chance that I wanted per level.

Have a nice day.

**Comment by Xaikii** [comment]
Hey :)

thanks for the Suggestion, the Enchantment you describe is probably Midas Blessing, and if you mean increase the drops of EVERYTHING, than that's already a no, as it's simply game breaking at it's best.
Remember that this would duplicate every machine and whatnot.

**Comment by edotenseilove** [comment]
Thank you for your answer. I understand your concern. I guess similar results might be achievable with Midas blessing, config.

I am really sorry for bothering you again. I tried Midas blessing I did not change the config file but Midas blessing was not working on the latest version for 1.19.2 gold counter increased after the addition of gold but when I mined gem ore ( I tried it on coal diamond emerald) I did not get additional drops and the counter did not go down.

**Comment by Xaikii** [comment]
I'll look into it :)

**Comment by edotenseilove** [comment]
Thank you:-)

**Comment by Xaikii** [comment]
Sry for the late response, I was able to confirm it and I did release a new version that fixes this :)
I also changed it to apply on all ores instead of only gems

**Comment by edotenseilove** [comment]
Thank you. it is amazing.

Have a great day.
