### ISSUE TITLE
Where is item code's?

### ISSUE THREAD

**Issue by wibonsue** [TinyModularThings/UniqueEnchantments#76]
Hello i want to use /give for my server
This is usually what u do for gettin enchanted book example a sharpness IV
/give @p enchanted_book{Enchantments:[{id:protection,lvl:4}]} 1
i tried somethings but still i couldnt get is this possible or not if it is not please add item code

**Comment by Speiger** [comment]
@wibonsue do you have op rights?

**Comment by Xaikii** [comment]
what?

**Comment by Xaikii** [comment]
After re-reading this multiple times, I genuinely do not understand what you're asking for, neither what an "item code" is supposed to be.

**Comment by wibonsue** [comment]
it is normal if u dont know what is item code so basically there is codes that every item has in minecraft
so if you want grass block from /give the item code or item name is minecraft:grass_block so it would like this
/give @p minecraft:grass_block you can use
every item has this and most of the mods that have items have this to so did you understand what is item code that i mean?

**Comment by wibonsue** [comment]
it is a little complicated when its comes to enchant books if you do this /give @p enchanted_book it will give you normal book
but if you do this /give @p enchanted_book{Enchantments:[{id:protection,lvl:4}]} it will give you Protection IV
so enchantment books have their own codes to but like what should i do if i want Ambrosia IV from /give ?
i tried to do /give @p enchanted_book{Enchantments:[{id:ambrosia,lvl:4}]} but didnt worked

**Comment by wibonsue** [comment]
i mean i want to get ambrosia from /give because i have server and plugins so what is item code of ambrosia
or other things that mod has what is item code how can i get it from /give

**Comment by Speiger** [comment]
@wibonsue you need to include the modid if you don't provide the modid it will default to minecraft:ambrosia which unique enchantments doesn't use.
Look at the "EnchantCommand" to find out which modid we use  for which specific enchantment.

**Comment by Xaikii** [comment]
/give @p enchanted_book{StoredEnchantments:[{id:"uniqueutil:ambrosia",lvl:4}]}
is what you're looking for

**Comment by wibonsue** [comment]
speiger where can i look to it

**Comment by Speiger** [comment]
use the /enchant command @wibonsue

**Comment by wibonsue** [comment]
![2022-12-22_23 52 15](https://user-images.githubusercontent.com/89047094/209232370-902a6950-7c75-4398-86ed-8e7258d9beae.png) this ?

**Comment by wibonsue** [comment]
there is only this thing happens when i use /enchant

**Comment by Speiger** [comment]
@wibonsue https://www.youtube.com/watch?v=ZDQmog-Ei8o

**Comment by wibonsue** [comment]
my problem solved btw thanks

**Comment by wibonsue** [comment]
i have one more question how can i apply it to dried kelp like how can i get it from /give again i tried this
/give @p minecraft:dried_kelp{Enchantments:[{id:uniqueutil:ambrosia,lvl:4}

**Comment by Xaikii** [comment]
I gave you the exact command for what you wanted above

/give @p enchanted_book{StoredEnchantments:[{id:"uniqueutil:ambrosia",lvl:4}]}

**Comment by wibonsue** [comment]
yes but how can i get enchanted dried kelp enchanted dried kelp with ambrosia IV

**Comment by wibonsue** [comment]
i tried this either /give @p minecraft:dried_kelp{Enchantments:[{id:uniqueutil:ambrosia,lvl:4}]}
and /give @p minecraft:dried_kelp{StoredEnchantments:[{id:uniqueutil:ambrosia,lvl:4}]}
but didnt worked

**Comment by wibonsue** [comment]
sorry im exhausting you but this is really important for my server

**Comment by Xaikii** [comment]
You first asked for the Enchanted Book, I gave you the command for the Enchanted Book... 

/give @p minecraft:dried_kelp{Enchantments:[{id:"uniqueutil:ambrosia",lvl:4}]}

**Comment by Speiger** [comment]
Please look into how minecraft commands actually work. This is essential knowledge we don't have to teach you.
Minecrafts autocomplete options also show you exactly how our ids work.
At this point please use Google foo instead of us to painstakingly explain you each step how to do your stuff.
As if we would be doing it.

Sorry but locking the issue because its resolved.
