### ISSUE TITLE
[Question] How can i set vitae's hp custom

### ISSUE THREAD

**Issue by wibonsue** [TinyModularThings/UniqueEnchantments#79]
Hello there is a server called GamiFun and they using your mod and i have a question
When i put Vitae 5 to my armor it gives 20hp on their server
But when i try it on my server with same version of the mod it gives me only 5 hp
how can i set hp giving amount of vitae like them ?

**Comment by Speiger** [comment]
Read the config file. Everything is configurable.

**Comment by wibonsue** [comment]
Where is config file ?

**Comment by Xaikii** [comment]
config folder --> ue --> UE.toml

on the github wiki you'll find all the necessary informations, like the formula of said Enchantment.
And with the config you can then customize it.

**Comment by wibonsue** [comment]
![image_2023-01-02_163719337](https://user-images.githubusercontent.com/89047094/210238712-43e00466-f59b-4161-bc7f-6e10f6c80e6e.png)
What should i change here to make hp 20
(im sorry if im being annoying but i cant read wiki my english is really bad)

**Comment by Colin-J-Wood** [comment]
Vitae works based on how many XP levels you currently have, and is going to scale against that.

so, reasonably, you're only getting 5hp on your server because, unlike your singleplayer test, you have less XP there than you did on singleplayer.

raise your player's level to increase the health boost.

read the wiki for more specifics.

**Comment by wibonsue** [comment]
bro i have 6600 LvL in my server i dont think the point is lvls cuz it doesnt matter what level you are on GamiFun server

**Comment by Xaikii** [comment]
@wibonsue do you want to have 20 HP when having 4x Vitae 5, or when only a single Vitae 5 applied?

**Comment by wibonsue** [comment]
İ want each vitae piece gives 20hp like 
when i put my vitea 5 boots it gives 20
with helmet +20 more total 80 with all piece
Only single vitae 5 gives 20hp

**Comment by Xaikii** [comment]
> İ want each vitae piece gives 20hp like when i put my vitea 5 boots it gives 20 with helmet +20 more total 80 with all piece Only single vitae 5 gives 20hp

What you're asking for completely missed the point of the balance for said Enchantment.
Change "BaseBoost" to ``97033038`` and there you have it

**Comment by wibonsue** [comment]
Yess thanks you
