### ISSUE TITLE
Some tooltips are incorrect

### ISSUE THREAD

**Issue by katubug** [TinyModularThings/UniqueEnchantments#8]
I'm not certain what adds these tooltips, perhaps JEI Integration or Enchantment Descriptions? I'm afraid I don't have time to test right now. However, as you can see below, Phoenix's Blessing says "Anything" in the place where it tells you what can be enchanted with it. And Ender Librarian says "Fishing Rod."

I have tested, and the enchantments actually do apply to the correct items, it's just the tooltip that's incorrect. These are the only two I've found so far.

![2020-01-30_19 22 38](https://user-images.githubusercontent.com/20935286/73504724-ef2b4580-4395-11ea-88ce-feff37758000.png)
![2020-01-30_19 22 45](https://user-images.githubusercontent.com/20935286/73504725-ef2b4580-4395-11ea-8313-fdc088cbae63.png)

**Comment by Speiger** [comment]
Oh yeah, eh that totally has a very good reason its that case.
MC has only limited options for what tool types are supported 
https://github.com/TinyModularThings/UniqueEnchantments/blob/1.12.2/src/main/java/uniquee/enchantments/unique/EnchantmentEnderLibrarian.java#L14
So we had to pick one. Fishing rod seemed reasonable ^^"

**Comment by katubug** [comment]
Ah, okay, that makes sense. Thanks for explaining! :)
