### ISSUE TITLE
Ares Grace causes extra durability damage to weapons

### ISSUE THREAD

**Issue by colerosemergy** [TinyModularThings/UniqueEnchantments#81]
Not sure if this is intended or not, but at the very least I can't find where it is listed IF it is intended.

**Comment by Xaikii** [comment]
intended

**Comment by Xaikii** [comment]
https://github.com/TinyModularThings/UniqueEnchantments/wiki/Ares-Grace
It doesnt tell it in description, but look at the formula

**Comment by Xaikii** [comment]
Description will be adjusted for next update, ty

**Comment by NighthowlerStudios** [comment]
additionally, it's a vanilla mechanic that high damage shots already do a lot more durability damage to armor.  so make sure you're testing against relatively low damage

**Comment by Xaikii** [comment]
@Kaleidio weapon, not armor

**Comment by NighthowlerStudios** [comment]
ah right

**Comment by colerosemergy** [comment]
Thanks!
