### ISSUE TITLE
1.12 Request for removing tooltip "hold to open" option

### ISSUE THREAD

**Issue by darchitectlp** [TinyModularThings/UniqueEnchantments#83]
Holding a menu key to slowly take you to the the JEI tab for Unique Enchantments "use" page is a waste of time. It takes a 3 second button hold to do what can be done instantaneously. When the user can just click the "use" key on the item and then the tab in JEI, why sit there and wait 3 seconds? Plus, the tool tip note clutters up the item tooltip (especially when we already have Enchantment Descriptions installed).

This is just a request to have a config option so I can turn off the tool tip portion. Love the enchants, though. Thanks!

**Comment by Xaikii** [comment]
The time to hold said button is configurable, that being said config to remove that thing is already on our todo list

**Comment by darchitectlp** [comment]
Awesome. Thanks!
