### ISSUE TITLE
Icons' compatibility issue with Apotheosis.

### ISSUE THREAD

**Issue by wasdspace** [TinyModularThings/UniqueEnchantments#86]
Mods: [Unique+Enchantments+Base-1.16.5-1.4.3.1](https://legacy.curseforge.com/minecraft/mc-mods/unique-enchantments-base), [Apotheosis-1.16.5-4.8.9A0](https://legacy.curseforge.com/minecraft/mc-mods/apotheosis), [Placebo-1.16.5-4.7.1](https://legacy.curseforge.com/minecraft/mc-mods/placebo/files/4501015)

![2023-04-28_20 05 19](https://user-images.githubusercontent.com/85009668/235144769-ee6ce0ca-875b-4c01-be4b-40d919f95345.png)

Only the icons inside the enchantment table are displayed with problems.

**Comment by Speiger** [comment]
@wasdspace Apotheosis doesn't support custom fonts which is a Vanilla Minecraft feature.
Not a UE bug but a Apotheosis Bug.
