### ISSUE TITLE
Icons' compatibility issue with ModernUI.

### ISSUE THREAD

**Issue by wasdspace** [TinyModularThings/UniqueEnchantments#87]
Mods: [Unique+Enchantments+Base-1.16.5-1.4.3.1](https://legacy.curseforge.com/minecraft/mc-mods/unique-enchantments-base), [ModernUI-1.16.5-2.7.1.105](https://legacy.curseforge.com/minecraft/mc-mods/modern-ui/files/3765938)

![2023-04-28_19 50 42](https://user-images.githubusercontent.com/85009668/235145971-21fd28f9-5be5-4d6a-9e39-2a2e7c4a6a00.png)

**Comment by Speiger** [comment]
@wasdspace moderUI doesn't support custom fonts which is a Vanilla Minecraft feature.
Not a UE bug but a Modern UI Bug.

**Comment by Xaikii** [comment]
To correct Speiger here:
Modern UI overwrites the Font used, the Icons are done with Fonts.
This is an inherent incompat, you need to change the font used itself and not overwrite it

**Comment by Speiger** [comment]
To Correct Xaikii:
He doesn't test if the Font being set was already overriden, AKA he blindly just overrides all fonts being set.
All he has to do is: "Is this a custom font? Yes? Then don't override it. No? Then override it"
