### ISSUE TITLE
[1.19.2] Conflicting with Apothesis

### ISSUE THREAD

**Issue by itsdinkd** [TinyModularThings/UniqueEnchantments#88]
Botania + Apothesis + aquamirae + Unique Enchantments Conflict.

https://gist.github.com/itsdinkd/80070021f6204c40709b8d837d515123 (Conflicting w/o Botania, but with Unique Enchantments and Apothesis while Enchantment Module is on). This crash occurs when trying to create a single player world.

https://gist.github.com/itsdinkd/939ef9bc5eb54a243b0140e29a94e192 (Crashes on launch, added botania, disabled enchantment module on Apothesis)

https://github.com/Shadows-of-Fire/Apotheosis/issues/875

**Comment by Speiger** [comment]
@itsdinkd known issue.
We just have a giant patch that is being developed and it awaits a few libraries.
But its fixed in the latest "INDEV UNRELEASED" build

**Comment by Glimmering-Melon** [comment]
same problem

**Comment by Speiger** [comment]
fixed
