### ISSUE TITLE
Suggestions for localization changes (1.12.2)

### ISSUE THREAD

**Issue by katubug** [TinyModularThings/UniqueEnchantments#9]
Hi! Sorry to make so many issues all at once, haha. I figured I'd get it over with. :) I was taking a look at the mod's lang file to make some changes for my personal preferences (changing Ameliorated to Superior), but I thought it might be helpful for me to share my alterations.

Some of the descriptions contain incorrect information, misspellings, or grammatical/syntactical errors, which I corrected to the best of my knowledge. I also made them consistent to vanilla's enchantment descriptions by removing the capitalization of non-proper nouns and adding a period to the end of each.

The one thing I didn't fix is the fact that Ender Librarian is listed twice - I was worried that if I didn't override both entries in my resource lang file, one of the incorrect versions would overwrite them. :) I did remove the bit about Treasure Maps, since those don't exist in 1.12.

Anyway, here are my changes: https://gist.github.com/katubug/f2e1030c48805082f777f042b618f454

Please forgive me for not doing a full-on PR, I was too lazy to fork the whole project just for a lang file. :P

**Comment by Speiger** [comment]
o.O Thanks for the work first.

Eh if something is duplicated then its just replacing the first one.
Nothing to worry about. 
About the lang file has to be validated by @Xaikii too.
And as long its tiny changes like that its fine.
If xaikii approves too I would like to ask you if you could do the same for the 1.14 version?

**Comment by Xaikii** [comment]
Honestly these descriptions are much better than mine ^^'
a few thing to correct here and there tho, which are also my fault due to awful descriptions which led to missunderstandings.
Swift Blade & Focus Impact do not change the attack speed. They only deal additional damage scaling with attack speed. Also Death's Odium will only grant your health temporarily back if it's the same item you died with, having any other Death's Odium Item won't work (Or at least it isnt intended to work).
Also I am questioning a bit the Alchemists Grace description, as those aren't random ^^'

**Comment by katubug** [comment]
Thanks a bunch for all the corrections! I've edited the gist to reflect those changes.

As to the Alchemist's Grace, I had missed the part in the config where the potion effects are specified per enchantment level. I just saw a handful of them, but only got three during my testing, and assumed it was a random chance. xD So thank you for the correction!

As to Death's Odium, that makes sense! When I was testing it, I enchanted a full set of armor + a weapon with it, haha. So that explains why only one piece affected the lost HP! Now I understand.

I'll take a look at the 1.14 version as well, now :D

**Comment by katubug** [comment]
Okay, I copied down the uploaded lang file for 1.14 Forge and migrated my changes over. I did make sure to add back in the Treasure Map behavior for Ender Librarian.

Both files are now at this link: https://gist.github.com/katubug/f2e1030c48805082f777f042b618f454

If you guys want any more help, feel free to let me know!

**Comment by Speiger** [comment]
@katubug 3 months late. But 1.12.2 has now the new language file

**Comment by Snapshotlight** [comment]
What's more, I think those descriptions are not clear. I hope that there will be clearer descriptions that give the effect of each enchantments. For example, the description of Ameliorated Sharpness just said "an advanced version of sharpness" which makes me confused and do not give the effect of this enchantments. 
So please make the description clearer.

**Comment by Speiger** [comment]
@Snapshotlight If you have improvements submit them. As long as they seem reasonable there is nothing against taking them into the mod.
