### ISSUE TITLE
[1.16.5] two mod conflicts appothelous and evilcraft

### ISSUE THREAD

**Issue by Natedogwoooof** [TinyModularThings/UniqueEnchantments#91]
[crash-2023-08-10_00.21.28-client.txt](https://github.com/TinyModularThings/UniqueEnchantments/files/12313882/crash-2023-08-10_00.21.28-client.txt)
[crash-2023-08-10_08.17.49-client.txt](https://github.com/TinyModularThings/UniqueEnchantments/files/12313884/crash-2023-08-10_08.17.49-client.txt)

**Comment by Xaikii** [comment]
both not our fault if you read the crash
