### ISSUE TITLE
i cant found ameliorated sharpness's enchant id

### ISSUE THREAD

**Issue by wibonsue** [TinyModularThings/UniqueEnchantments#93]
Hello i need to find ameliorated sharpness's enchant i tried /enchant and looked all enchants there but literally there was every any other enchants other than ameliorated sharpness what is ameliorated sharpness's enchant id or how do i look ?

**Comment by Speiger** [comment]
https://github.com/TinyModularThings/UniqueEnchantments/blob/1.19/src/main/java/uniquee/enchantments/simple/AmelioratedSharpness.java#L20C26-L20C47

**Comment by Speiger** [comment]
if 1.19.2 is not correct simply switch to the mc version you use, the classpath is the same.

**Comment by wibonsue** [comment]
its 1.16.5 how can i get it to my inventory with /enchant command?
/enchant ameliorated_sharpness didnt worked

**Comment by wibonsue** [comment]
/enchant uniquee_ameliorated_sharpness also this and /enchant uniquee:ameliorated_sharpness this didnt worked to

**Comment by Speiger** [comment]
@Xaikii your turn... Layer 8 issue

**Comment by Xaikii** [comment]
`/enchant PLAYERNAME uniquee:all`

**Comment by wibonsue** [comment]
let me try real quick

**Comment by Speiger** [comment]
a typical PICNIC issue, TL:DR RTFM

**Comment by wibonsue** [comment]
It said you are not holding any item and when i tried to hold some enchanted book it said enchanted books cannot be support that enchant or something what should i do ? @Xaikii

**Comment by Xaikii** [comment]
> It said you are not holding any item and when i tried to hold some enchanted book it said enchanted books cannot be support that enchant or something what should I do ? @Xaikii

That command is used to enchantment an item that can take that Enchantment.

To give yourself an enchanted book with an Enchantment:
`/give @p enchanted_book{StoredEnchantments:[{id:'enchantmentIDhere',lvl:5}]} 1`

**Comment by wibonsue** [comment]
![2023-09-18_22 57 01](https://github.com/TinyModularThings/UniqueEnchantments/assets/89047094/14d13658-18b3-42c7-990b-64884e958931)
it said same error again :/

> > It said you are not holding any item and when i tried to hold some enchanted book it said enchanted books cannot be support that enchant or something what should I do ? @Xaikii
> 
> That command is used to enchantment an item that can take that Enchantment.
> 
> To give yourself an enchanted book with an Enchantment: `/give @p enchanted_book{StoredEnchantments:[{id:'enchantmentIDhere',lvl:5}]} 1`

**Comment by Xaikii** [comment]
`/give @p enchanted_book{StoredEnchantments:[{id:'uniquee:all',lvl:5}]} 1`
Use this command exactly

**Comment by Xaikii** [comment]
NVM, issue on my side:
`/give @p enchanted_book{StoredEnchantments:[{id:'uniquee:ameliorated_sharpness',lvl:5}]} 1`

**Comment by Xaikii** [comment]
If this doesnt work, then something is wrong on your side

**Comment by wibonsue** [comment]
no it just gives me normal enchanted book and every other uniquee enchants like vitae or something i can get them from /give but all "Ameliorated" enchants like ameliorated sharpness,ameliorated smite, Ameliorated bane of arthropod not showing on /enchant i can get any other enchants from uniquee but only ameliorated ones cant.

> NVM, issue on my side: `/give @p enchanted_book{StoredEnchantments:[{id:'uniquee:ameliorated_sharpness',lvl:5}]} 1`

**Comment by wibonsue** [comment]
oh this one worked thanks.

> `/give @p enchanted_book{StoredEnchantments:[{id:'uniquee:all',lvl:5}]} 1` Use this command exactly
