### ISSUE TITLE
Apex Entchantments keep disapearing

### ISSUE THREAD

**Issue by Flox-40** [TinyModularThings/UniqueEnchantments#94]
When I hold an item with an Apex Enchantment it disapears after a few seconds. It does hold on books. Does this happen to anyone else?

**Comment by Speiger** [comment]
Not a bug. That just happens if you got the enchantments illegitimately.

You need to do the fusion otherwise the enchantments simply get deleted.

**Comment by Flox-40** [comment]
Thank you🙂

Speiger ***@***.***> schrieb am Sa., 6. Jän. 2024, 00:24:
