### ISSUE TITLE
Clarity on what causes Apex enchantments to disappear

### ISSUE THREAD

**Issue by curtissimo41** [TinyModularThings/UniqueEnchantments#98]
I read in a previously closed issue that the Apex enchantments will disappear if they are obtained illegitimately. However, in my single player world, when I used enchantment fusion to create a Blessed Blade II book, then added it to my sword with an anvil (all legitimately), it still made the enchantment disappear. It worked when I performed the enchantment fusion directly onto the sword rather than going through the book + anvil. Could there be some clarity provided for this? I'm not sure why obtaining the enchantment on a book, then adding it to a tool with the anvil, would be considered illegitimate.

**Comment by Gilsoun** [comment]
I play on a server, and with me the enchantments also disappear, I have prints showing that the enchantments were not obtained illegitimately.
![image](https://github.com/TinyModularThings/UniqueEnchantments/assets/126258654/c4ef1391-a048-409f-89b7-6540ebde5ab7)

![image](https://github.com/TinyModularThings/UniqueEnchantments/assets/126258654/ca7104a1-8ac6-403e-850d-dca6ead5f3a5)

![image](https://github.com/TinyModularThings/UniqueEnchantments/assets/126258654/f8d5b95a-e384-4041-b37d-82a824c0b16d)

**Comment by Speiger** [comment]
You need to apply it not via book. That will not transfer the "validity bit"

**Comment by Gilsoun** [comment]
I understand, the difficulty is just to collect the items to perform the fusion and then the enchantment disappears, thank you for responding :)

**Comment by Gilsoun** [comment]
now it doesn't disappear, thank you very much 😎👍

![image](https://github.com/TinyModularThings/UniqueEnchantments/assets/126258654/c8016f39-c2d2-4f04-aa45-d27847bfd994)
