### ISSUE TITLE
[1.19.2 BETA] Apotheosis Conflict Data

### ISSUE THREAD

**Issue by Godric-Tobrecan** [TinyModularThings/UniqueEnchantments#99]
This is all done on 1.19.2, ofc.

**First Set**

Trial 1
Mods: (291)
Apotheosis-1.19.2-6.4.1.jar
apotheotic_additions1.0.3.1_v1.19.2.jar
Placebo-1.19.2-7.3.5.jar
Patchouli-1.19.2-77.jar
Unique_Enchantments-1.19.2-Beta.jar (first discord beta)
(many others, I can provide full list if requested)

Damaged an elk, did 25 damage. Elk also one shotted me.

Trial 2
Mods: (290)
Apotheosis-1.19.2-6.4.1.jar
apotheotic_additions1.0.3.1_v1.19.2.jar
Placebo-1.19.2-7.3.5.jar
Patchouli-1.19.2-77.jar
(many others, I can provide full list if requested)

Damaged an elk, did 1 damage. Elk hit me, I lived, then I closed the game.

**Second Set**
Done with a fresh install, only listed mods. Forge Version 43.3.13

Trial 1
Mods: (3)
Apotheosis-1.19.2-6.5.0.jar
Placebo-1.19.2-7.4.0.jar
Patchouli-1.19.2-77.jar

Loaded into world fine, no issues.

Trial 2
Mods: (4)
Apotheosis-1.19.2-6.5.0.jar
Placebo-1.19.2-7.4.0.jar
Patchouli-1.19.2-77.jar
Unique_Enchantments-1.19.2-Beta.jar (first discord beta)

CTD on on start (before main menu)

Here's Log for Set 2 Trial 2.
[latest.log](https://github.com/TinyModularThings/UniqueEnchantments/files/15044764/latest.log)

So far not enough data to draw an exact conclusion, but working hypotheses are:
1) The beta require some mods that (listed in logs) are in my 291 modpack. 
2) When used with Apotheosis and required mods, the damage multiplier is still insane.

**Comment by Speiger** [comment]
fixed
